# Generated by Django 3.2.15 on 2023-03-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_defaulttemplate_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttemplate',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
