# Generated by Django 4.0.4 on 2023-04-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='private_liked_memes',
            field=models.BooleanField(default=True),
        ),
    ]
