# Generated by Django 4.0.4 on 2023-04-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_profile_private_liked_memes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='private_liked_memes',
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_meme_privacy',
            field=models.CharField(choices=[('Private', 'Private'), ('Friends Only', 'Friends Only'), ('Public', 'Public')], default='Private', max_length=15, null=True),
        ),
    ]
