# Generated by Django 4.0.4 on 2023-04-18 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_liked_meme_privacy_profile_liked_memes_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='requestee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_requests', to='main.profile'),
        ),
    ]
