# Generated by Django 4.0.4 on 2023-05-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_time',
            field=models.DateTimeField(null=True),
        ),
    ]
